raw-spans-grouper perf tuning
hypertrace/raw-spans-grouper pull request #33
Opened 2020-11-03 12:10 UTC by laxmanchekka

2020-11-03 13:36 UTC, jcchavezs commented on helm/values.yaml
> +        cacheMaxBytesBuffering: "104857600"
This value seems a bit arbitrary, do you mind elaborating on why exactly this value? Also I wonder if this should be a string instead of an int.

2020-11-03 13:39 UTC, jcchavezs requested changes
How about adding more context on why this is needed or the problem being solved and how those values solve it?

2020-11-04 06:26 UTC, laxmanchekka commented
@jcchavezs : Main idea was to templatize few important kafka streams configurations.
Yes. 100 MB need not be the default value. Default values has to be minimal to be able to run on smaller clusters.

Will update the PR and mark it for review.

2020-11-09 04:26 UTC, kotharironak commented
As part of consolidating repos in PR - https://github.com/hypertrace/hypertrace-ingester/pull/15, closing this. Pl. re-port

2020-11-09 04:26 UTC, closed without merging